# Generated by Django 6.0.4 on 2026-04-21 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_type', models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back'), ('SIDE', 'Side')], default='FRONT', max_length=10)),
                ('image_url', models.URLField(help_text='S3 or Firebase URL of the base product image', max_length=1024)),
                ('print_area', models.JSONField(default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='MockupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, help_text='Celery Task ID', max_length=255, null=True)),
                ('user_design_url', models.URLField(help_text='Firebase/S3 URL of user uploaded design', max_length=1024)),
                ('result_image_url', models.URLField(blank=True, help_text='URL of generated mockup', max_length=1024, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productimage')),
            ],
        ),
    ]
