# Generated by Django 6.0.4 on 2026-04-23 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('design_image', models.ImageField(help_text='Uploaded 2D design decal', upload_to='customizer/designs/')),
                ('preview_snapshot', models.ImageField(blank=True, help_text='3D snapshot image', null=True, upload_to='customizer/snapshots/')),
                ('decal_position', models.JSONField(default=dict)),
                ('decal_rotation', models.JSONField(default=dict)),
                ('decal_scale', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mockupjob',
            name='user_design_url',
        ),
        migrations.AddField(
            model_name='mockupjob',
            name='user_design',
            field=models.ImageField(help_text='Uploaded user design', null=True, upload_to='designs/'),
        ),
        migrations.AlterField(
            model_name='mockupjob',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productimage'),
        ),
    ]
